### ISSUE TITLE
Test Ticket

### ISSUE THREAD

**Issue by valentinajemuovic** [alptium/marija.bircevic#1]
Hi @MarijaBircevic,

Please do the following:

1. Write a comment below that you have received this test ticket.
2. Please tag me using @ then typing my GitHub name.
3. Then close this ticket.

Thanks,
Valentina

**Comment by valentinajemuovic** [comment]
@MarijaBircevic, did you try the tasks above, see my first comment.

**Comment by MarijaBircevic** [comment]
I  received this test ticket @valentinacupac

**Comment by MarijaBircevic** [comment]
I'm sorry, I forgot about that mail. I did it now.
