### ISSUE TITLE
CodingBat - Warmup-1 

### ISSUE THREAD

**Issue by MarijaBircevic** [alptium/marija.bircevic#12]

**Comment by MarijaBircevic** [comment]
@valentinacupac  I have finished code practice Warmup-1.
![coding bat](https://user-images.githubusercontent.com/35116168/37556867-541954ba-29fc-11e8-9f22-4af6a5af7c68.png)

**Comment by valentinajemuovic** [comment]
@MarijaBircevic, correct.
